// export const color1 = '#D9E4EC'
// export const color2 = '#B7CFDC'
// export const color3 = '#6AABD2'
// export const color4 = '#385E72'

// export const color1 = '#2b4560'
// export const color2 = '#e1e7e0'
// export const color3 = '#6aa4b0'
// export const color4 = '#2f6d80'


// export const color2 = '#a3cef1'
// export const color3 = '#6096ba'
// export const color1 = '#e7ecef'
// export const color4 = '#e7ecef'

export const tableRowEvenColor = '#a9d6e5'
export const tableRowOddColor = '#89c2d9'
export const tableHeaderColor = '#468faf'
// export const tableBGColor = '#f2f1ef'
export const tabSidebarBGInactiveColor = '#2a6f97'
export const tabSidebarBGActiveColor = '#468faf'
export const tabSidebarTextColor = '#ffffff'
export const tableTextColor = '#012a4a'
export const headlineTextColor = '#012a4a'
export const creditReqBadColor = '#ed6890'
export const creditReqGoodColor = '#68ed90'
export const creditReqHeaderColor = '#e0e0e0'
export const planpageBGColor = '#e1f5ff'


// export const tableRowEvenColor = '#d9e4ec'
// export const tableRowOddColor = '#b7cfdc'
// export const tableHeaderColor = '#6aabd2'
// // export const tableBGColor = '#f2f1ef'
// export const tabSidebarBGInactiveColor = '#c0c0c0' 
// export const tabSidebarBGActiveColor = '#6aabd2'
// export const tabSidebarTextColor = '#ffffff'
// export const tableTextColor = '#012a4a'
// export const headlineTextColor = '#012a4a'