-- -- data.sql

-- Insert data into StudyPlan table
INSERT INTO study_plan (plan_name) VALUES ("מדעי המחשב");
INSERT INTO study_plan (plan_name) VALUES ("מדעי המחשב - אבטחת המרחב המקוון");
INSERT INTO study_plan (plan_name) VALUES ("מדעי המחשב - מדעי הנתונים");
INSERT INTO study_plan (plan_name) VALUES ("מדעים בהדגשת מדעי המחשב");


-- Insert data into Course table
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מתמטיקה בדידה: תורת הקבוצות, קומבינטוריקה ותורת הגרפים",  20476, "מתמטיקה", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אלגברה לינארית 1",  20109, "מתמטיקה", 7);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אלגברה לינארית 2",  20229, "מתמטיקה", 5);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("חשבון אינפיניטסימלי 1",  20474, "מתמטיקה", 7);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("חשבון אינפיניטסימלי 2",  20475, "מתמטיקה", 7);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("הסתברות ומבוא לסטטיסטיקה למדעי המחשב",  20425, "מתמטיקה", 5);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא למדעי המחשב ושפת Java",  20441, "מדעי המחשב", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבני נתונים ומבוא לאלגוריתמים",  20407, "מדעי המחשב", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אלגוריתמים",  20417, "מדעי המחשב", 5);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מעבדה בתכנות מערכות",  20465, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אוטומטים ושפות פורמליות",  20440, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לתורת החישוביות והסיבוכיות",  20585, "מדעי המחשב מתקדם", 5);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("ארגון המחשב",  20471, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("לוגיקה למדעי המחשב",  20466, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מערכות הפעלה",  20594, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("שפות תכנות",  20905, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מערכות בסיסי-נתונים",  20277, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("עקרונות פיתוח מערכות מידע",  20436, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("תורת הקודים",  20296, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אנליזה נומרית 1",  20462, "מדעי המחשב", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לבינה מלאכותית",  20551, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("תכנות מדעי המחשב מתקדם בשפת Java",  20554, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לרשתות תקשורת מחשבים",  20582, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("תכנות מערכות דפנסיבי",  20937, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("גרפיקה ממוחשבת",  20562, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לקריפטוגרפיה",  20580, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("קומפילציה",  20364, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("תכנות מונחה עצמים",  20906, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מערכות נתונים - טכנולוגיות ואלגוריתמים",  20574, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("חישוביות ביולוגית",  20581, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("כריית מידע",  20595, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אנליזה נומרית 2",  20900, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא ללמידה חישובית",  20942, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("רובוטיקה אלגוריתמית",  20944, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לאבטחת המרחב המקוון",  20940, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לבדיקות תוכנה (אנגלית) ",  20946, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אשנב למחקר במדעי המחשב למצטיינים",  20945, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("פרקי העשרה למצטיינים 1",  20996, "מדעי המחשב מתקדם", 1);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("פרקי העשרה למצטיינים 2",  20997, "מדעי המחשב מתקדם", 1);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("פרקי העשרה למצטיינים 3",  20998, "מדעי המחשב מתקדם", 1);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("פרקי העשרה למצטיינים 4",  20999, "מדעי המחשב מתקדם", 1);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בהנדסת תוכנה",  20368, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר באנליזה נומרית",  20369, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בחישוביות",  20370, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר במערכות בסיסי-נתונים",  20371, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בבינה מלאכותית",  20372, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בקריפטוגרפיה",  20374, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בנושא מיוחד במדעי המחשב",  20375, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בתקשורת/אלגוריתמים מבוזרים",  20388, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר במערכות הפעלה",  20389, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר באלגוריתמים",  20390, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בביו-אינפורמטיקה",  20552, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר: ממדעי המחשב להוראתם - רקע, התפתחות וסוגיות נבחרות",  20560, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר במערכות מקביליות",  20583, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר מצטיינים במדעי המחשב ובמדעי הקוגניציה",  20921, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר במערכות מידע",  20373, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר באבטחת המרחב המקוון",  20927, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר בבינה חישובית",  20922, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סמינר במדעי המחשב (אנגלית) ",  20954, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה בתכנות מונחה עצמים",  20586, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה בתכנות מתקדם בשפת Java",  20503, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה בבסיסי-נתונים",  20563, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה במערכות הפעלה",  20587, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה בתקשורת מחשבים",  20588, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה במדעי הנתונים",  20936, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה באבטחת מידע",  20931, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("סדנה בטכנולוגיות לפיתוח אפליקציות לענן ולרשת",  20995, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לראייה ממוחשבת",  22928, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("נושאים מתקדמים באבטחת המרחב המקוון",  22939, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אבטחת מערכות תוכנה",  22923, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("הסקה סטטיסטית",  30204, "מתמטיקה", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("למידה עמוקה",  22961, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("עיבוד תמונה",  22913, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("ארכיטקטורות חישוב בהשראת המוח",  22960, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אלגוריתמים לנתוני עתק",  22934, "מדעי המחשב מתקדם", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לסטטיסטיקה ולהסתברות למדעים",  30203, "מתמטיקה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("תורת ההסתברות",  20416, "מתמטיקה", 5);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("חשבון דיפרנציאלי ואינטגלי א׳",  20406, "מתמטיקה", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("חשבון דיפרנציאלי ואינטגלי ב׳",  20423, "מתמטיקה", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("אלגברה ליניארית לתלמידי מדעים",  20430, "מתמטיקה", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא למחשבת ישראל",  10809, "מדעי הרוח", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לארכיאולוגיה של ארץ ישראל",  10140, "מדעי הרוח", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא למוסיקה א׳",  10148, "מדעי הרוח", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא למיקרוכלכלה",  10131, "כלכלה", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא למקרוכלכלה",  10126, "כלכלה", 4);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("מבוא לפסיכולוגיה",  10136, "פסיכולוגיה", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("יסודות הפיסיקה א׳",  20113, "פיסיקה", 3);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("יסודות הפיסיקה ",  20125, "פיסיקה", 6);
Insert INTO Course (name, number, credits_type, credits_number) VALUES ("יסודות הפיסיקה לביולוגים א׳",  20123, "פיסיקה", 3);

-- Insert data into Dependency table
INSERT INTO Dependency (dependent_course, base_course) VALUES (20229, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20475, "20474");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20425, "20475, 20406");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20407, "20441, 20478, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20407, "20476");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20417, "20109, 20430");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20417, "20407");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20465, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20440, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20440, "20476");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20585, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20585, "20440");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20471, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20466, "20476");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20594, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20594, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20905, "20407");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20905, "20440");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20905, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20905, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20277, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20277, "20476, 10444");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20436, "20277");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20296, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20462, "20441, 20453, 20478");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20462, "20109, 20430");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20462, "20474, 20406");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20462, "20475, 20423");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20551, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20551, "20466, 20327, 10444");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20551, "20425, 20416, 30203");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20554, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20582, "20425, 30203, 30111, 20416");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20582, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20937, "20554");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20937, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20937, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20562, "20474");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20562, "20475");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20562, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20562, "20407");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20562, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20580, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20580, "20425");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20580, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20364, "20440");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20364, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20906, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20574, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20574, "20277");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20581, "30203, 20425");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20581, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20581, "20406, 20474");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20581, "20109, 20430");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20595, "20425, 30203");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20595, "20407, 20433");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20900, "20462");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20942, "30203, 20425");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20942, "20474");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20942, "20475");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20942, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20942, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20109");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20229");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20474");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20475");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20441");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20944, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20940, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20940, "20582");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20946, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20946, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20946, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20371, "20277");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20921, "10679");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20921, "10615");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20921, "20425");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20921, "20441, 20454");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20921, "30204, 20286");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20927, "20554");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20927, "20582");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20922, "20407");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20922, "20551");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20586, "20554, 20906");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20503, "20554");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20563, "20277");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20587, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20588, "20582");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20588, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20936, "20425, 30204");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20936, "20551");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20936, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20931, "20582");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20931, "20940");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20995, "20417");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20995, "20465");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20995, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (22939, "20580, 20940, 22923");
INSERT INTO Dependency (dependent_course, base_course) VALUES (22923, "20277");
INSERT INTO Dependency (dependent_course, base_course) VALUES (22923, "20594");
INSERT INTO Dependency (dependent_course, base_course) VALUES (30204, "30203, 20425, 20416");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20416, "20474, 20406");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20416, "20475, 20423");
INSERT INTO Dependency (dependent_course, base_course) VALUES (20423, "20406, 20492");
INSERT INTO Dependency (dependent_course, base_course) VALUES (22961, "20595");


-- Insert data into Mandatory_Requirement table
-- Plan #1
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20476);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20109);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20229);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20474);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20475);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20425);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20441);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20407);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20417);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20465);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20440);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20585);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20471);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20466);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20594);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (1, 20905);

-- Plan #2
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20476);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20109);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20229);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20474);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20475);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20425);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20441);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20407);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20417);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20465);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20440);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20585);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20471);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20466);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20594);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20905);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20580);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20582);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20937);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20940);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, "20927, 20954");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (2, 20931);

-- Plan #3
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20476);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20109);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20229);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20474);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20475);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20425);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20441);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20407);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20417);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20465);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20440);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20585);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20471);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20466);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20594);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20905);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 30204);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20277);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20942);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20595);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 22961);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, "20372, 20375, 20922, 20954");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (3, 20936);

-- Plan #4
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, "20406, 20474");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, "20423, 20475");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, "20430, 20109");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, 20476);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, "30203, 20425");
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, 20441);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, 20407);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, 20417);
INSERT INTO mandatory_requirement (plan_id, course_number) VALUES (4, 20466);

-- Insert data into Credits_Requirement table
-- Plan #1
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מתמטיקה", 35);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מדעי המחשב", 76);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מדעי המחשב מתקדם", 27);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מדעים", 111);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (1, "כללי", 120);

-- Plan #2
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מתמטיקה", 35);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מדעי המחשב", 76);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מדעי המחשב מתקדם", 40);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מדעים", 111);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (2, "כללי", 120);

-- Plan #3
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מתמטיקה", 35);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מדעי המחשב", 80);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מדעי המחשב מתקדם", 39);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מדעים", 115);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מדעי המחשב מתקדם סמינריוני סדנה", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "מדעי המחשב מתקדם סמינריוני סמינר", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (3, "כללי", 121);

-- Plan #4
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מתמטיקה", 23);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מדעי המחשב", 61);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מדעי המחשב מתקדם", 23);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מדעים", 96);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "פיסיקה", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מדעים מתקדם", 27);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "מרחיב דעת", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "סמינריונית", 3);
INSERT INTO credits_requirement (plan_id, credits_type, credits_number) VALUES (4, "כללי", 120);


-- Insert data into Credit_Types table
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעי המחשב","מדעי המחשב, מדעי המחשב מתקדם");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעים", "פיסיקה, מתמטיקה, מדעי המחשב, מדעי המחשב מתקדם, מדעי המחשב מתקדם סמינריוני סדנה, מדעי המחשב מתקדם סמינריוני סמינר, מדעים מתקדם");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעי המחשב מתקדם סמינריוני סמינר", "מדעי המחשב מתקדם סמינריוני סמינר");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעי המחשב מתקדם סמינריוני סדנה", "מדעי המחשב מתקדם סמינריוני סדנה");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעי המחשב מתקדם","מדעי המחשב מתקדם");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מתמטיקה","מתמטיקה");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מדעים מתקדם","מדעי המחשב מתקדם");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("סמינריונית","מדעי המחשב מתקדם סמינריוני סדנה, מדעי המחשב מתקדם סמינריוני סמינר");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("פיסיקה","פיסיקה");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("מרחיב דעת","כלכלה, פסיכולוגיה, מדעי הרוח");
INSERT INTO credit_types (credits_type, sub_type) VALUES ("כללי","פיסיקה, מתמטיקה, מדעי המחשב, מדעי המחשב מתקדם, מדעי המחשב מתקדם סמינריוני סדנה, מדעי המחשב מתקדם סמינריוני סמינר, מדעים מתקדם, כללי, כלכלה, פסיכולוגיה, מדעי הרוח");



